import * as vscode from 'vscode';
import * as fs from 'fs';
import { PrNoirPanel } from '../webview/panel';
import { ReviewResult } from '../types';

function formatTimestamp(ts: number): string {
  return new Date(ts).toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
}

function buildMarkdown(result: ReviewResult): string {
  const criticalCount = result.comments.filter(c => c.severity === 'critical').length;
  const warnCount = result.comments.filter(c => c.severity === 'warn').length;
  const infoCount = result.comments.filter(c => c.severity === 'info').length;

  const findings = result.comments.map(c => {
    const location = c.line ? `${c.file}:${c.line}` : c.file;
    let block = `### [${c.severity.toUpperCase()}] ${c.title} — ${location}\n`;
    block += `**Type:** ${c.type}\n`;
    block += `**Description:** ${c.description}\n`;
    if (c.suggestion) {
      block += `**Suggestion:**\n\`\`\`\n${c.suggestion}\n\`\`\`\n`;
    }
    return block;
  }).join('\n');

  const dupes = result.duplicates.map((d, i) => {
    const files = d.files.map(f => `\`${f}\``).join(', ');
    const lines = d.lineRanges.join(', ');
    let block = `### Block ${i + 1}\n`;
    block += `**Files:** ${files}\n`;
    if (lines) block += `**Lines:** ${lines}\n`;
    block += `**Description:** ${d.description}\n`;
    return block;
  }).join('\n');

  return [
    '# PR Noir Review Report',
    `Generated: ${formatTimestamp(result.timestamp)}`,
    '',
    '## Summary',
    `**Score:** ${result.score}/100`,
    result.summary,
    '',
    '## Score Breakdown',
    '| Severity | Count |',
    '|---|---|',
    `| Critical | ${criticalCount} |`,
    `| Warn | ${warnCount} |`,
    `| Info | ${infoCount} |`,
    '',
    '## Findings',
    '',
    findings || '_No findings._',
    '',
    '## Duplicate Blocks',
    '',
    dupes || '_No duplicate blocks detected._',
    '',
    '---',
    '_Generated by PR Noir v1.0.0_',
    '',
  ].join('\n');
}

export async function exportMarkdown(): Promise<void> {
  const result = PrNoirPanel.lastResult;
  if (!result) {
    vscode.window.showWarningMessage('PR Noir: No review to export. Run a review first.');
    return;
  }

  const uri = await vscode.window.showSaveDialog({
    defaultUri: vscode.Uri.file('pr-noir-review.md'),
    filters: { Markdown: ['md'] },
  });

  if (!uri) return;

  try {
    fs.writeFileSync(uri.fsPath, buildMarkdown(result), 'utf8');
    const openDoc = await vscode.window.showInformationMessage(
      `PR Noir: Review exported to ${uri.fsPath}`,
      'Open File'
    );
    if (openDoc === 'Open File') {
      const doc = await vscode.workspace.openTextDocument(uri);
      vscode.window.showTextDocument(doc);
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    vscode.window.showErrorMessage(`PR Noir: Export failed — ${message}`);
  }
}
